export const ERRORS = {
  USER_EXISTS: 'USER_EXISTS',
  ACCOUNT_NOT_LINKED: 'ACCOUNT_NOT_LINKED',
  USER_EMAIL_NOT_FOUND: 'USER_EMAIL_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND'
} as const;
