// Error codes the API puts in a GraphQL error's `extensions.code`
export const ERRORS = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  USER_EXISTS: 'USER_EXISTS',
  ACCOUNT_NOT_LINKED: 'ACCOUNT_NOT_LINKED',
  USER_EMAIL_NOT_FOUND: 'USER_EMAIL_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID'
} as const;

export type ErrorCode = (typeof ERRORS)[keyof typeof ERRORS];
