export const transactions = [
  {
    name: "Badrallach Campsite",
    date: "29/05/21",
    amount: 5.4,
    status: "PENDING",
    negative: true,
  },
  {
    name: "The Range",
    date: "31/05/21",
    amount: 14.98,
    status: "PENDING",
    negative: true,
  },
  {
    name: "Cooper Bros",
    date: "31/05/21",
    amount: 58.01,
    status: "PENDING",
    negative: true,
  },
  {
    name: "Graeme Baxter - car",
    date: "01/06/21",
    amount: 141.67,
    status: "COMPLETE",
    negative: false,
  },
  {
    name: "McDonalds",
    date: "27/05/21",
    amount: 13.64,
    status: "COMPLETE",
    negative: true,
  },
  {
    name: "Kenneth Baxter - The Range",
    date: "31/05/21",
    amount: 15.0,
    status: "COMPLETE",
    negative: false,
  },
  {
    name: "Graeme Baxter - Spotify",
    date: "31/05/21",
    amount: 5.0,
    status: "COMPLETE",
    negative: false,
  },
  {
    name: "Optical Express",
    date: "28/05/21",
    amount: 157.0,
    status: "COMPLETE",
    negative: true,
  },
];
